<?xml version="1.0" encoding="utf-8"?>
<Project>
    <Import Project="$(MSBuildThisFileDirectory)node_modules/@rimworks/mod-ci/msbuild/GameVersion.props"
            Condition="Exists('$(MSBuildThisFileDirectory)node_modules/@rimworks/mod-ci/msbuild/GameVersion.props')" />

    <Target Name="RequireModCi" BeforeTargets="ResolveAssemblyReferences" Condition="'$(GameVersion)' == ''">
        <Error Text="mod-ci is not installed. run: npm install" />
    </Target>

    <PropertyGroup>
        <Authors>RimWorks</Authors>
        <Company>RimWorks</Company>
        <Copyright>Copyright (c) 2026 RimWorks</Copyright>
        <PackageProjectUrl>https://github.com/RimWorks/rimworld-logging-framework</PackageProjectUrl>
        <RepositoryUrl>https://github.com/RimWorks/rimworld-logging-framework</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <TargetFramework>net48</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <WarningLevel>4</WarningLevel>
        <ErrorReport>prompt</ErrorReport>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <FileAlignment>512</FileAlignment>

        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <PlatformTarget Condition=" '$(Platform)' == '' ">AnyCPU</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    </PropertyGroup>

    <ItemDefinitionGroup Condition="'$(IsTestProject)' != 'true'">
        <Reference>
            <Private>False</Private>
        </Reference>
        <ProjectReference>
            <Private>False</Private>
        </ProjectReference>
        <PackageReference>
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
    </ItemDefinitionGroup>

    <ItemGroup>
        <PackageReference Include="SonarAnalyzer.CSharp" Version="10.34.*" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Linq"/>
        <Using Include="System.Collections.Generic"/>
    </ItemGroup>
</Project>
