name: dependabot-automerge

on: pull_request_target

permissions:
  contents: read

jobs:
  automerge:
    permissions:
      contents: write
      pull-requests: write
    uses: RimWorks/mod-ci/.github/workflows/dependabot-automerge.yml@d6261858b6b74c0cd3ca03c6402c954d58ac7fee # v1.5.1
