name: dependabot-automerge

on: pull_request_target

permissions:
  contents: read

jobs:
  automerge:
    permissions:
      contents: write
      pull-requests: write
    uses: RimWorks/mod-ci/.github/workflows/dependabot-automerge.yml@f10430c71960ac8d11c9cfb4b5b31cdfbc83cab9 # v1.5.2
