name: ship-list

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    uses: RimWorks/mod-ci/.github/workflows/ship-list.yml@f10430c71960ac8d11c9cfb4b5b31cdfbc83cab9 # v1.5.2
    with:
      ref: f10430c71960ac8d11c9cfb4b5b31cdfbc83cab9 # v1.5.2
